---
 - name: install nginx on RedHat
   hosts: RedHat_Servers
   vars:
     package_names: "nginx"
   gather_facts: yes
   become: yes
   tags:
     - redhat
   tasks:
     - name: installing nginx on RedHat
       yum:
         name: "{{ package_names }}"
         state: latest

     - name: start nginx service
       service:
         name: "{{ package_names }}"
         state: started
       tags:
         - nginx_redhat

     - name: print os family of target server
       debug:
         msg: "{{ ansible_os_family }}"
       tags:
         - ubuntu

     - name: copy file to target servers
       template:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
       notify: restart the service
       loop:
         - { src: index.html.j2, dest: /var/www/html/index.nginx-debian.html }
       tags:
         - redhat

  

 - name: create linux user with password
   hosts: all
   become: true
   vars_files:
    - secrets.yml
   tasks:
    - name: Create user account
      user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        home: "/home/{{ username }}"
        create_home: yes
        state: present
        expires: -1
